import { ImageType, ProductSchemaType, MenuCategorySchemaType, ImageSchemaType, IngredientSchemaType, ProductIngredientSchemaType } from "@/app/lib/definitions";

/*NOTE This file is for generating data objects to be seeded into the database. Maybe I'll change the name now that
the main purpose for this file has changed from creating and exporting the data locally? */

const heroImage: ImageType = {
  src: '/assets/home/images/hero/pizza_hero.jpg',
  alt: 'Giant Pizza.',
  width: 1300,
  height: 956
}

const menuCategoryDbSeedItems: MenuCategorySchemaType[] = [];
const productDbSeedItems: ProductSchemaType[] = [];
const imageDbSeedItems: ImageSchemaType[] = [];
const ingredientDbSeedItems: IngredientSchemaType[] = [];
const productIngredientDbSeedItems: ProductIngredientSchemaType[] = [];

function generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType {
  return {
    id: 0, // This is a placeholder. Will be generated by db product table.
    name,
    description,
    category,
    href,
    paramName,
    imgId,
    price
  }
}

function generateMenuCategoryDbSeedItem(name: string, category: string, href: string, imgId: number): MenuCategorySchemaType {
  return {
    id: 0, // This is a placeholder. Will be generated by db menu table.
    name,
    category,
    href,
    imgId
  }
}

function generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType {
  return {
    id: 0, // This is a placeholder. Will be generated by db image table.
    src,
    alt,
    width,
    height
  }
}

function generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType {
  return {
    id: 0, // This is a placeholder. Will be generated by db ingredient table.
    name,
    category,
    imgId,
    price
  }
}

function generateProductIngredientDbSeedItem(productId: number, ingredientId: number) {
  return {
    productId,
    ingredientId
  }
}

//#region Menu categories for db menu_category table to be used by menu page. 

// generateMenuCategoryDbSeedItem(name: string, category: string, href: string, imgId: number): MenuCategorySchemaType
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Build Your Own Pizza', 'build-your-own-pizza', '/menu/build_your_own_pizza', 1));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Specialty Pizzas', 'specialty', '/menu/specialty_pizza', 2));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Breads', 'bread', '/menu/bread', 3));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Chicken Wings', 'chicken', '/menu/chicken', 4));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Pasta', 'pasta', '/menu/pasta', 5));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Sandwiches', 'sandwich', '/menu/sandwich', 6));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Salads', 'salad', '/menu/salad', 7));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Desserts', 'dessert', '/menu/dessert', 8));
menuCategoryDbSeedItems.push(generateMenuCategoryDbSeedItem('Drinks', 'drinks', '/menu/drink', 9));
// #endregion

//#region Individual product items for db product table by category

// -- Pizza

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Pepperoni', 'Yummy Pepperoni', 'specialty', '/menu/specialty_pizza/pepperoni', 'pepperoni', 10, 1499));
productDbSeedItems.push(generateProductDbSeedItem('Supreme', 'Yummy Supreme', 'specialty', '/menu/specialty_pizza/supreme', 'supreme', 11, 1699));
productDbSeedItems.push(generateProductDbSeedItem('Meat Lovers', 'Yummy Meat Lovers', 'specialty', '/menu/specialty_pizza/meat-lovers', 'meat-lovers', 12, 1899));
productDbSeedItems.push(generateProductDbSeedItem('6-Cheese', 'Yummy 6-Cheese', 'specialty', '/menu/specialty_pizza/6-cheese', '6-cheese', 13, 1399));
productDbSeedItems.push(generateProductDbSeedItem('Veggie Lovers', 'Yummy Veggie Lovers', 'specialty', '/menu/specialty_pizza/veggie-lovers', 'veggie-lovers', 14, 1799));
productDbSeedItems.push(generateProductDbSeedItem('BBQ Chicken', 'Yummy BBQ Chicken', 'specialty', '/menu/specialty_pizza/bbq-chicken', 'bbq-chicken', 15, 1799));
productDbSeedItems.push(generateProductDbSeedItem('Chicken Bacon Ranch', 'Yummy Chicken Bacon Ranch', 'specialty', '/menu/specialty_pizza/chicken-bacon-ranch', 'chicken-bacon-ranch', 16, 1799));

// -- Bread

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Breadsticks', 'Yummy Breadsticks', 'bread', '/menu/bread/breadsticks', 'breadsticks', 17, 499));
productDbSeedItems.push(generateProductDbSeedItem('Cheesy Bread', 'Yummy Cheesy Bread', 'bread', '/menu/bread/cheesy-bread', 'cheesy-bread', 18, 699));
productDbSeedItems.push(generateProductDbSeedItem('Bread Bites', 'Yummy Bread Bites', 'bread', '/menu/bread/bread-bites', 'bread-bites', 19, 599));
productDbSeedItems.push(generateProductDbSeedItem('Cinnamon Bread Bites', 'Yummy Cinnamon Bread Bites', 'bread', '/menu/bread/cinnamon-bread-bites', 'cinnamon-bread-bites', 20, 599));

// -- Chicken

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Plain Wings', 'Yummy Plain Wings', "chicken", '/menu/chicken/plain-wings', 'plain-wings', 21, 899));
productDbSeedItems.push(generateProductDbSeedItem('Hot Wings', 'Yummy Hot Wings', "chicken", '/menu/chicken/hot-wings', 'hot-wings', 22, 899));
productDbSeedItems.push(generateProductDbSeedItem('BBQ Wings', 'Yummy BBQ Wings', "chicken", '/menu/chicken/bbq-wings', 'bbq-wings', 23, 899));
productDbSeedItems.push(generateProductDbSeedItem('Buffalo Wings', 'Yummy Buffalo Wings', "chicken", '/menu/chicken/buffalo-wings', 'buffalo-wings', 24, 899));
productDbSeedItems.push(generateProductDbSeedItem('Garlic Parmesan Wings', 'Yummy Garlic Parmesan Wings', "chicken", '/menu/chicken/garlic-parmesan-wings', 'garlic-parmesan-wings', 25, 899));
productDbSeedItems.push(generateProductDbSeedItem('Boneless Wings', 'Yummy Boneless Wings', "chicken", '/menu/chicken/boneless-wings', 'boneless-wings', 26, 999));
productDbSeedItems.push(generateProductDbSeedItem('Zesty Asian Wings', 'Yummy Zesty Asian Wings', "chicken", '/menu/chicken/zesty-asian-wings', 'zesty-asian-wings', 27, 899));

// -- Pasta

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Chicken Alfredo', 'Yummy Chicken Alfredo', 'pasta', '/menu/pasta/chicken-alfredo', 'chicken-alfredo', 28, 1099));
productDbSeedItems.push(generateProductDbSeedItem('5-Cheese Mac & Cheese', 'Yummy 5-Cheese Mac & Cheese', 'pasta', '/menu/pasta/5-cheese-mac-n-cheese', '5-cheese-mac-n-cheese', 29, 999));
productDbSeedItems.push(generateProductDbSeedItem('Spicy Buffalo 5-Cheese Mac & Cheese', 'Yummy Spicy Buffalo 5-Cheese Mac & Cheese', 'pasta', '/menu/pasta/spicy-buffalo-5-cheese-mac-n-cheese', 'spicy-buffalo-5-cheese-mac-n-cheese', 30, 999));
productDbSeedItems.push(generateProductDbSeedItem('Spaghetti & Meatballs', 'Yummy Spaghetti & Meatballs', 'pasta', '/menu/pasta/spaghetti-n-meatballs', 'spaghetti-n-meatballs', 31, 1099));

// -- Sandwich

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Chicken Parm', 'Yummy Chicken Parm', 'sandwich', '/menu/sandwich/chicken-parm', 'chicken-parm', 32, 899));
productDbSeedItems.push(generateProductDbSeedItem('Chicken Bacon Ranch', 'Yummy Chicken Bacon Ranch', 'sandwich', '/menu/sandwich/chicken-bacon-ranch', 'chicken-bacon-ranch', 33, 899));
productDbSeedItems.push(generateProductDbSeedItem('Italian', 'Yummy Italian', 'sandwich', '/menu/sandwich/italian', 'italian', 34, 899));
productDbSeedItems.push(generateProductDbSeedItem('Buffalo Chicken', 'Yummy Buffalo Chicken', 'sandwich', '/menu/sandwich/buffalo-chicken', 'buffalo-chicken', 35, 899));
productDbSeedItems.push(generateProductDbSeedItem('Philly Cheesesteak', 'Yummy Philly Cheesesteak', 'sandwich', '/menu/sandwich/philly-cheesesteak', 'philly-cheesesteak', 36, 899));

// -- Salad

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Classic Garden', 'Yummy Classic Garden', 'salad', '/menu/salad/classic-garden', 'classic-garden', 37, 799));
productDbSeedItems.push(generateProductDbSeedItem('Chicken Caesar', 'Yummy Chicken Caesar', 'salad', '/menu/salad/chicken-caesar', 'chicken-caesar', 38, 899));

// -- Dessert

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Chocolate Lava Cake', 'Yummy Chocolate Lave Cake', 'dessert', '/menu/dessert/chocolate-lava-cake', 'chocolate-lava-cake', 39, 499));
productDbSeedItems.push(generateProductDbSeedItem('Chocolate Cookie Brownies', 'Yummy Chocolate Cookie Brownies', 'dessert', '/menu/dessert/chocolate-cookie-brownies', 'chocolate-cookie-brownies', 40, 499));
productDbSeedItems.push(generateProductDbSeedItem('Cinnamon Bread Bites', 'Yummy Cinnamon Bread Bites', 'dessert', '/menu/dessert/cinnamon-bread-bites', 'cinnamon-bread-bites', 41, 599));

// -- Drinks

// generateProductDbSeedItem(name: string, description: string, category: string, href: string, paramName: string, imgId: number, price: number): ProductSchemaType
productDbSeedItems.push(generateProductDbSeedItem('Pepsi', 'Yummy Pepsi', 'drinks', '/menu/drink/pepsi', 'pepsi', 42, 399));
productDbSeedItems.push(generateProductDbSeedItem('Mountain Dew', 'Yummy Mountain Dew', 'drinks', '/menu/drink/mountain-dew', 'mountain-dew', 43, 399));
productDbSeedItems.push(generateProductDbSeedItem('Mug Root Beer', 'Yummy Mug Root Beer', 'drinks', '/menu/drink/mug-root-beer', 'mug-root-beer', 44, 399));
productDbSeedItems.push(generateProductDbSeedItem('Dr Pepper', 'Yummy Dr Pepper', 'drinks', '/menu/drink/dr-pepper', 'dr-pepper', 45, 399));
productDbSeedItems.push(generateProductDbSeedItem('Cherry Pepsi', 'Yummy Cherry Pepsi', 'drinks', '/menu/drink/cherry-pepsi', 'cherry-pepsi', 46, 399));
productDbSeedItems.push(generateProductDbSeedItem('Orange Crush', 'Yummy Orange Crush', 'drinks', '/menu/drink/orange-crush', 'orange-crush', 47, 399));
// #endregion

// #region Images for db image table

// -- Menu Categories

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/specialty-category.jpg', 'Build Your Own Pizza Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/specialty-category.jpg', 'Pizza Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Bread Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Chicken Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/pasta/pasta-category.jpg', 'Pasta Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/sandwich/sandwich-category.jpg', 'Sandwich Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/salad/salad-category.jpg', 'Salad Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/dessert/dessert-category.jpg', 'Dessert Menu Category', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Drinks Menu Category', 800, 800));

// -- Pizza

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/pepperoni.jpg', 'Pepperoni Pizza', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/supreme.jpg', 'Supreme Pizza', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/meat-lovers.jpg', 'Meat Lovers', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/6-cheese.jpg', '6-Cheese', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/veggie-lovers.jpg', 'Veggie Lovers', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/bbq-chicken.jpg', 'BBQ Chicken', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/specialty/chicken-bacon-ranch.jpg', 'Chicken Bacon Ranch', 800, 800));

// -- Bread

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Breadsticks', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Cheesy Bread', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Bread Bites', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Cinnamon Bread Bites', 800, 800));

// -- Chicken

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Plain Wings', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Hot Wings', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'BBQ Wings', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Buffalo Wings', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Garlic Parmesan Wings', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Boneless Wings', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/chicken/chicken-category.jpg', 'Zesty Asian Wings', 800, 800));

// -- Pasta

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/pasta/pasta-category.jpg', 'Chicken Alfredo', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/pasta/pasta-category.jpg', '5-Cheese Mac & Cheese', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/pasta/pasta-category.jpg', 'Spicy Buffalo 5-Cheese Mac & Cheese', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/pasta/pasta-category.jpg', 'Spaghetti & Meatballs', 800, 800));

// -- Sandwich

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/sandwich/sandwich-category.jpg', 'Chicken Parm', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/sandwich/sandwich-category.jpg', 'Chicken Bacon Ranch', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/sandwich/sandwich-category.jpg', 'Italian', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/sandwich/sandwich-category.jpg', 'Buffalo Chicken', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/sandwich/sandwich-category.jpg', 'Philly Cheesesteak', 800, 800));

// -- Salad

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/salad/salad-category.jpg', 'Classic Garden', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/salad/salad-category.jpg', 'Chicken Caesar', 800, 800));

// -- Dessert

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/dessert/dessert-category.jpg', 'Chocolate Lava Cake', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/dessert/dessert-category.jpg', 'Chocolate Cookie Brownies', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/dessert/dessert-category.jpg', 'Cinnamon Bread Bites', 800, 800));

// -- Drinks

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Pepsi', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Mountain Dew', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Mug Root Beer', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Dr Pepper', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Cherry Pepsi', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/drinks/drinks-category.jpg', 'Orange Crush', 800, 800));

// -- Ingredients

// -- -- Crust

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Hand Tossed Crust', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Parmesan Stuffed Crust', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Handmade Pan Crust', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Thin Crust', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'New York Style Crust', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Gluten Free Crust', 800, 800));

// -- -- Crust Seasoning

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Garlic Crust Seasoning', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'No Garlic Crust Seasoning', 800, 800));

// -- -- Sauce

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Robust Tomato Sauce', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Honey BBQ Sauce', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Garlic Parmesan Sauce', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Alfredo Sauce', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Ranch Dressing Sauce', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'No Sauce', 800, 800));

// -- -- Mozzarella

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Mozzarella Cheese', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'No Mozzarella Cheese', 800, 800));

// -- -- Meat

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Ham', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Beef', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Pepperoni', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Italian Sausage', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Chicken', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Bacon', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Philly Steak', 800, 800));

// -- -- Veggies & More

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Hot Buffalo Sauce', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Garlic', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Jalapeno Peppers', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Onions', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Banana Peppers', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Diced Tomatoes', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Black Olives', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Mushrooms', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Pineapple', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Green Peppers', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Spinach', 800, 800));

// -- -- Add-on Cheeses

// generateImageDbSeedItem(src: string, alt: string, width: number, height: number): ImageSchemaType
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Shredded Provolone', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Cheddar Cheese Blend', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Feta Cheese', 800, 800));
imageDbSeedItems.push(generateImageDbSeedItem('/assets/menu/bread/bread-category.jpg', 'Shredded Parmesan Asiago', 800, 800));

// #endregion

// #region Ingredients for ingredient db table by category

// -- Crust

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Hand Tossed Crust', 'crust', 1, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Parmesan Stuffed Crust', 'crust', 2, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Handmade Pan Crust', 'crust', 3, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Thin Crust', 'crust', 4, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('New York Style Crust', 'crust', 5, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Gluten Free Crust', 'crust', 6, 0));

// -- Crust Seasoning

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Garlic Crust Seasoning', 'crust-seasoning', 1, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('No Garlic Crust Seasoning', 'crust-seasoning', 2, 0));

// -- Sauce

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Robust Tomato Sauce', 'sauce', 1, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Honey BBQ Sauce', 'sauce', 2, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Garlic Parmesan Sauce', 'sauce', 3, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Alfredo Sauce', 'sauce', 4, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Ranch Dressing Sauce', 'sauce', 5, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('No Sauce', 'sauce', 6, 0));

// -- Mozzarella

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Mozzarella Cheese', 'mozzarella', 1, 0));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('No Mozzarella Cheese', 'mozzarella', 2, 0));

// -- Meat

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Ham', 'meat', 1, 100));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Beef', 'meat', 2, 100));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Pepperoni', 'meat', 3, 100));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Italian Sausage', 'meat', 4, 100));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Chicken', 'meat', 5, 100));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Bacon', 'meat', 6, 100));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Philly Steak', 'meat', 7, 100));

// -- Veggies & More

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Hot Buffalo Sauce', 'veggies-n-more', 1, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Garlic', 'veggies-n-more', 2, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Jalapeno Peppers', 'veggies-n-more', 3, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Onions', 'veggies-n-more', 4, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Banana Peppers', 'veggies-n-more', 5, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Diced Tomatoes', 'veggies-n-more', 6, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Black Olives', 'veggies-n-more', 7, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Mushrooms', 'veggies-n-more', 8, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Pineapple', 'veggies-n-more', 9, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Green Peppers', 'veggies-n-more', 10, 200));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Spinach', 'veggies-n-more', 11, 200));

// -- Add-on Cheeses

// generateIngredientDbSeedItem(name: string, category: string, imgId: number, price: number): IngredientSchemaType
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Shredded Provolone', 'cheese', 1, 300));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Cheddar Cheese Blend', 'cheese', 2, 300));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Feta Cheese', 'cheese', 3, 300));
ingredientDbSeedItems.push(generateIngredientDbSeedItem('Shredded Parmesan Asiago', 'cheese', 4, 300));

// #endregion

// #region Entries for product_ingredient table

// #region Specialty Pizzas

// Pepperoni

// generateProductIngredientDbSeedItem(productId: number, ingredientId: number)
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(1, 1));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(1, 7));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(1, 9));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(1, 15));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(1, 19));



// Supreme

// generateProductIngredientDbSeedItem(productId: number, ingredientId: number)
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 1));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 7));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 9));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 15));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 19));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 20));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 27));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 30));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 31));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(2, 33));

// #endregion

// #region Sandwiches

// Chicken Bacon Ranch

// generateProductIngredientDbSeedItem(productId: number, ingredientId: number)
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(24, 9));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(24, 15));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(24, 21));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(24, 22));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(24, 35));

// Italian

// generateProductIngredientDbSeedItem(productId: number, ingredientId: number)
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 15));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 17));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 19));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 27));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 28));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 33));
productIngredientDbSeedItems.push(generateProductIngredientDbSeedItem(25, 35));


// #endregion

// #endregion

export { heroImage, productDbSeedItems, menuCategoryDbSeedItems, imageDbSeedItems, ingredientDbSeedItems, productIngredientDbSeedItems };